---
sections:
  - title: "VHDLTest Requirements"
    sections:
      - title: "Command-Line Interface"
        requirements:
          - id: "CLI-001"
            title: "The tool shall provide a command-line interface."
            tests:
              - "Options_ParseArguments_NoArguments_ReturnsDefaultOptions"
              - "Options_ParseArguments_WithConfig_SetsConfigFile"

          - id: "CLI-002"
            title: "The tool shall display version information when requested."
            tests:
              - "Version_GetVersion_ReturnsValidVersion"

          - id: "CLI-003"
            title: "The tool shall display help information when requested."
            tests:
              - "Usage_WriteUsage_ContainsRequiredElements"

          - id: "CLI-004"
            title: "The tool shall support silent mode to suppress console output."
            tests:
              - "Options_ParseArguments_WithSilent_SetsSilentFlag"

          - id: "CLI-005"
            title: "The tool shall support verbose mode for detailed output."
            tests:
              - "Options_ParseArguments_WithVerbose_SetsVerboseFlag"

          - id: "CLI-006"
            title: "The tool shall allow specification of configuration files."
            tests:
              - "Options_ParseArguments_WithConfig_SetsConfigFile"

          - id: "CLI-007"
            title: "The tool shall allow specification of test results output file."
            tests:
              - "Options_ParseArguments_WithResults_SetsResultsFile"

          - id: "CLI-008"
            title: "The tool shall allow specification of simulator to use."
            tests:
              - "Options_ParseArguments_WithSimulator_SetsSimulator"

          - id: "CLI-009"
            title: "The tool shall support exit-0 mode to always exit with code 0."
            tests:
              - "Options_ParseArguments_WithExit0_SetsExit0Flag"

      - title: "Configuration File Processing"
        requirements:
          - id: "CFG-001"
            title: "The tool shall process YAML configuration files."
            tests:
              - "ConfigDocument_Load_ValidFile_LoadsSuccessfully"
              - "ConfigDocument_Load_WithFiles_LoadsFileList"

          - id: "CFG-002"
            title: "The tool shall read VHDL file lists from configuration."
            tests:
              - "ConfigDocument_Load_WithFiles_LoadsFileList"

          - id: "CFG-003"
            title: "The tool shall read test bench lists from configuration."
            tests:
              - "ConfigDocument_Load_WithTests_LoadsTestList"

          - id: "CFG-004"
            title: "The tool shall handle missing configuration files with appropriate error messages."
            tests:
              - "ConfigDocument_Load_NonExistentFile_ThrowsFileNotFoundException"

      - title: "Simulator Support"
        requirements:
          - id: "SIM-001"
            title: "The tool shall support the GHDL simulator."
            tests:
              - "GhdlSimulator_Constructor_CreatesSimulator"
              - "GhdlSimulator_DetectVersion_ReturnsVersionString"
              - "ubuntu-latest@ghdl"
              - "windows-latest@ghdl"

          - id: "SIM-002"
            title: "The tool shall support the ModelSim simulator."
            tests:
              - "ModelSimSimulator_Constructor_CreatesSimulator"

          - id: "SIM-003"
            title: "The tool shall support the Vivado simulator."
            tests:
              - "VivadoSimulator_Constructor_CreatesSimulator"

          - id: "SIM-004"
            title: "The tool shall support the ActiveHDL simulator."
            tests:
              - "ActiveHdlSimulator_Constructor_CreatesSimulator"

          - id: "SIM-005"
            title: "The tool shall support the NVC simulator."
            tests:
              - "NvcSimulator_Constructor_CreatesSimulator"
              - "NvcSimulator_DetectVersion_ReturnsVersionString"
              - "ubuntu-latest@nvc"
              - "windows-latest@nvc"

          - id: "SIM-006"
            title: "The tool shall detect simulator versions."
            tests:
              - "GhdlSimulator_DetectVersion_ReturnsVersionString"
              - "NvcSimulator_DetectVersion_ReturnsVersionString"

          - id: "SIM-007"
            title: "The tool shall create appropriate simulator instances based on configuration."
            tests:
              - "SimulatorFactory_CreateSimulator_Ghdl_CreatesGhdlSimulator"
              - "SimulatorFactory_CreateSimulator_ModelSim_CreatesModelSimSimulator"
              - "SimulatorFactory_CreateSimulator_Vivado_CreatesVivadoSimulator"
              - "SimulatorFactory_CreateSimulator_ActiveHdl_CreatesActiveHdlSimulator"
              - "SimulatorFactory_CreateSimulator_Nvc_CreatesNvcSimulator"

          - id: "SIM-008"
            title: "The tool shall handle unsupported simulators with appropriate error messages."
            tests:
              - "SimulatorFactory_CreateSimulator_Unknown_ThrowsNotSupportedException"

      - title: "Test Execution"
        requirements:
          - id: "TEST-001"
            title: "The tool shall execute VHDL test benches."
            tests:
              - "Context_Run_WithTests_ExecutesTests"

          - id: "TEST-002"
            title: "The tool shall detect test bench pass/fail status."
            tests:
              - "RunProcessor_ProcessLine_PassMessage_ReturnsPassResult"
              - "RunProcessor_ProcessLine_FailMessage_ReturnsFailResult"

          - id: "TEST-003"
            title: "The tool shall generate test results in TRX format."
            tests:
              - "TestResults_WriteTrx_ValidResults_GeneratesTrxFile"
              - "TestResults_WriteTrx_WithTests_IncludesTestResults"

          - id: "TEST-004"
            title: "The tool shall aggregate multiple test results."
            tests:
              - "TestResults_AddResult_AddsTestToResults"
              - "TestResults_AddResults_AddsMultipleTests"

          - id: "TEST-005"
            title: "The tool shall track test execution time."
            tests:
              - "TestResult_Constructor_WithDuration_SetsDuration"
              - "TestResults_WriteTrx_WithTests_IncludesTestResults"

          - id: "TEST-006"
            title: "The tool shall capture test failure messages."
            tests:
              - "TestResult_Constructor_WithMessage_SetsMessage"
              - "TestResults_WriteTrx_WithFailures_IncludesFailureMessages"

          - id: "TEST-007"
            title: "The tool shall handle test execution errors appropriately."
            tests:
              - "TestResults_WriteTrx_WithFailures_IncludesFailureMessages"

      - title: "Test Output Processing"
        requirements:
          - id: "OUT-001"
            title: "The tool shall parse simulator output for test results."
            tests:
              - "RunProcessor_ProcessLine_PassMessage_ReturnsPassResult"
              - "RunProcessor_ProcessLine_FailMessage_ReturnsFailResult"

          - id: "OUT-002"
            title: "The tool shall recognize pass assertions in test output."
            tests:
              - "RunProcessor_ProcessLine_PassMessage_ReturnsPassResult"

          - id: "OUT-003"
            title: "The tool shall recognize failure assertions in test output."
            tests:
              - "RunProcessor_ProcessLine_FailMessage_ReturnsFailResult"

          - id: "OUT-004"
            title: "The tool shall categorize simulator output lines."
            tests:
              - "RunProcessor_ProcessLine_InfoMessage_ReturnsInfoResult"
              - "RunProcessor_ProcessLine_WarningMessage_ReturnsWarningResult"
              - "RunProcessor_ProcessLine_ErrorMessage_ReturnsErrorResult"

      - title: "Validation"
        requirements:
          - id: "VAL-001"
            title: "The tool shall support self-validation mode."
            tests:
              - "Options_ParseArguments_WithValidate_SetsValidateFlag"
              - "Validation_RunValidation_GeneratesReport"

          - id: "VAL-002"
            title: "The tool shall generate validation reports."
            tests:
              - "Validation_RunValidation_GeneratesReport"

          - id: "VAL-003"
            title: "The tool shall include system information in validation reports."
            tests:
              - "Validation_RunValidation_IncludesSystemInfo"

          - id: "VAL-004"
            title: "The tool shall execute validation tests."
            tests:
              - "Validation_RunTests_PassingTest_ReturnsSuccess"
              - "Validation_RunTests_FailingTest_ReturnsFailure"

      - title: "Exit Code Handling"
        requirements:
          - id: "EXIT-001"
            title: "The tool shall exit with code 0 on successful test execution."
            tests:
              - "ExitCode_AllTestsPass_ReturnsZero"

          - id: "EXIT-002"
            title: "The tool shall exit with non-zero code on test failures."
            tests:
              - "ExitCode_SomeTestsFail_ReturnsNonZero"

          - id: "EXIT-003"
            title: "The tool shall support exit-0 mode to override failure exit codes."
            tests:
              - "ExitCode_FailWithExit0_ReturnsZero"

      - title: "Platform Support"
        requirements:
          - id: "PLT-001"
            title: "The tool shall run on Ubuntu Linux operating systems."
            tests:
              - "ubuntu-latest@UnitTests"
              - "ubuntu-latest@ghdl"
              - "ubuntu-latest@nvc"

          - id: "PLT-002"
            title: "The tool shall run on Windows operating systems."
            tests:
              - "windows-latest@UnitTests"
              - "windows-latest@ghdl"
              - "windows-latest@nvc"

          - id: "PLT-003"
            title: "The tool shall support .NET 8.0 runtime."
            tests:
              - "net8.0@UnitTests"
              - "dotnet8.x@ghdl"
              - "dotnet8.x@nvc"

          - id: "PLT-004"
            title: "The tool shall support .NET 9.0 runtime."
            tests:
              - "net9.0@UnitTests"
              - "dotnet9.x@ghdl"
              - "dotnet9.x@nvc"

          - id: "PLT-005"
            title: "The tool shall support .NET 10.0 runtime."
            tests:
              - "net10.0@UnitTests"
              - "dotnet10.x@ghdl"
              - "dotnet10.x@nvc"
