---
sections:
  - title: "VHDLTest Requirements"
    sections:
      - title: "Command-Line Interface"
        requirements:
          - id: "CLI-001"
            title: "The tool shall display usage information when run without arguments."
            tests:
              - "Program_Run_NoArguments_DisplaysUsageAndReturnsError"

          - id: "CLI-002"
            title: "The tool shall display version information when requested."
            tests:
              - "Program_Run_WithVersionShort_DisplaysVersionAndReturnsSuccess"
              - "Program_Run_WithVersionLong_DisplaysVersionAndReturnsSuccess"

          - id: "CLI-003"
            title: "The tool shall display help information when requested."
            tests:
              - "Program_Run_WithHelpShort_DisplaysUsageAndReturnsSuccess"
              - "Program_Run_WithHelpQuestion_DisplaysUsageAndReturnsSuccess"
              - "Program_Run_WithHelpLong_DisplaysUsageAndReturnsSuccess"

      - title: "Test Execution"
        requirements:
          - id: "TEST-001"
            title: "The tool shall execute VHDL test benches and return zero exit code on success."
            tests:
              - "Program_Run_TestsPassed_ReturnsZeroExitCode"

          - id: "TEST-002"
            title: "The tool shall return non-zero exit code when compilation fails."
            tests:
              - "Program_Run_CompileError_ReturnsNonZeroExitCode"

          - id: "TEST-003"
            title: "The tool shall return non-zero exit code when tests fail."
            tests:
              - "Program_Run_TestExecutionError_ReturnsNonZeroExitCode"

          - id: "TEST-004"
            title: "The tool shall support exit-0 mode to always return zero exit code."
            tests:
              - "Program_Run_TestExecutionErrorWithExit0_ReturnsZeroExitCode"

      - title: "Validation"
        requirements:
          - id: "VAL-001"
            title: "The tool shall support self-validation mode."
            tests:
              - "Program_Run_WithValidate_PerformsValidationAndReturnsSuccess"
              - "Context_Create_WithValidate_SetsValidateFlag"

          - id: "VAL-002"
            title: "The tool shall support configurable validation report depth."
            tests:
              - "Program_Run_WithValidateAndDepth_PerformsValidationWithDepth"

          - id: "VAL-003"
            title: "The tool shall save validation results to file."
            tests:
              - "Program_Run_WithValidateAndResultsFile_SavesValidationResults"

          - id: "VAL-004"
            title: "The tool shall include system information in validation reports."
            tests:
              - "Program_Run_WithValidate_IncludesOSVersionInReport"

      - title: "Simulator Support"
        requirements:
          - id: "SIM-001"
            title: "The tool shall support the GHDL simulator."
            tests:
              - "SimulatorFactory_Get_GhdlSimulator_ReturnsGhdlSimulator"
              - "GhdlSimulator_SimulatorName_ReturnsGHDL"
              - "ubuntu-latest@ghdl"
              - "windows-latest@ghdl"

          - id: "SIM-002"
            title: "The tool shall support the ModelSim simulator."
            tests:
              - "SimulatorFactory_Get_ModelSimSimulator_ReturnsModelSimSimulator"
              - "ModelSimSimulator_SimulatorName_ReturnsModelSim"

          - id: "SIM-003"
            title: "The tool shall support the Vivado simulator."
            tests:
              - "SimulatorFactory_Get_VivadoSimulator_ReturnsVivadoSimulator"
              - "VivadoSimulator_SimulatorName_ReturnsVivado"

          - id: "SIM-004"
            title: "The tool shall support the ActiveHDL simulator."
            tests:
              - "SimulatorFactory_Get_ActiveHDLSimulator_ReturnsActiveHDLSimulator"
              - "ActiveHdlSimulator_SimulatorName_ReturnsActiveHDL"

          - id: "SIM-005"
            title: "The tool shall support the NVC simulator."
            tests:
              - "SimulatorFactory_Get_NVCSimulator_ReturnsNVCSimulator"
              - "NvcSimulator_SimulatorName_ReturnsNVC"
              - "ubuntu-latest@nvc"
              - "windows-latest@nvc"

      - title: "Platform Support"
        requirements:
          - id: "PLT-001"
            title: "The tool shall run on Ubuntu Linux operating systems."
            tests:
              - "ubuntu-latest@UnitTests"
              - "ubuntu-latest@ghdl"
              - "ubuntu-latest@nvc"

          - id: "PLT-002"
            title: "The tool shall run on Windows operating systems."
            tests:
              - "windows-latest@UnitTests"
              - "windows-latest@ghdl"
              - "windows-latest@nvc"

          - id: "PLT-003"
            title: "The tool shall support .NET 8.0 runtime."
            tests:
              - "net8.0@UnitTests"
              - "dotnet8.x@ghdl"
              - "dotnet8.x@nvc"

          - id: "PLT-004"
            title: "The tool shall support .NET 9.0 runtime."
            tests:
              - "net9.0@UnitTests"
              - "dotnet9.x@ghdl"
              - "dotnet9.x@nvc"

          - id: "PLT-005"
            title: "The tool shall support .NET 10.0 runtime."
            tests:
              - "net10.0@UnitTests"
              - "dotnet10.x@ghdl"
              - "dotnet10.x@nvc"
