---
# Bug report issue template for VHDLTest
# Used to collect structured information about bugs
name: ðŸ› Bug Report
description: Report a bug or unexpected behavior in VHDLTest
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out
        the form below to help us investigate and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug you encountered...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. With configuration '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here, such as configuration files, error messages, or logs.

        Please include relevant environment details such as:
        - VHDLTest version (e.g., 1.0.0)
        - HDL Simulator and version (e.g., GHDL 3.0.0)
        - Operating System (e.g., Windows, Linux, macOS)
        - .NET version (e.g., .NET 8.0)
      placeholder: |
        You can attach files by dragging and dropping them here.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: >
        By submitting this issue, you agree to follow our
        [Code of Conduct](https://github.com/demaconsulting/VHDLTest/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
