---
# Bug report issue template for VHDLTest
# Used to collect structured information about bugs
name: ðŸ› Bug Report
description: Report a bug or unexpected behavior in VHDLTest
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out
        the form below to help us investigate and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug you encountered...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. With configuration '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: VHDLTest Version
      description: What version of VHDLTest are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: dropdown
    id: simulator
    attributes:
      label: HDL Simulator
      description: Which HDL simulator are you using?
      options:
        - GHDL
        - ModelSim
        - Vivado
        - ActiveHDL
        - NVC
        - Other
        - Not applicable
    validations:
      required: true

  - type: input
    id: simulator-version
    attributes:
      label: Simulator Version
      description: What version of the simulator are you using (if applicable)?
      placeholder: "e.g., GHDL 3.0.0"

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - Linux
        - macOS
        - Other
    validations:
      required: true

  - type: input
    id: dotnet-version
    attributes:
      label: .NET Version
      description: What version of .NET are you using?
      placeholder: "e.g., .NET 8.0"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, such as configuration files, error messages, or logs.
      placeholder: |
        You can attach files by dragging and dropping them here.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: >
        By submitting this issue, you agree to follow our
        [Code of Conduct](https://github.com/demaconsulting/VHDLTest/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
