package VHDLTest {
    part def ActiveHdlSimulator {
        doc /* Active-HDL simulator integration. */

        comment sourceRef /* Source: src/DEMAConsulting.VHDLTest/Simulators/ActiveHdlSimulator.cs */
        comment testRef /* Test: test/DEMAConsulting.VHDLTest.Tests/Simulators/ActiveHdlSimulatorTests.cs */
        comment designRef /* Design: docs/design/vhdltest/simulators/active-hdl-simulator.md */
        comment verificationRef /* Verification: docs/verification/vhdltest/simulators/active-hdl-simulator.md */
        comment reqRef /* Requirements: docs/reqstream/vhdltest/simulators/active-hdl-simulator.yaml */
    }
}
