package VHDLTest {
    part def GhdlSimulator {
        doc /* GHDL simulator integration. */

        comment sourceRef /* Source: src/DEMAConsulting.VHDLTest/Simulators/GhdlSimulator.cs */
        comment testRef /* Test: test/DEMAConsulting.VHDLTest.Tests/Simulators/GhdlSimulatorTests.cs */
        comment designRef /* Design: docs/design/vhdltest/simulators/ghdl-simulator.md */
        comment verificationRef /* Verification: docs/verification/vhdltest/simulators/ghdl-simulator.md */
        comment reqRef /* Requirements: docs/reqstream/vhdltest/simulators/ghdl-simulator.yaml */
    }
}
