package VHDLTest {
    part def ModelSimSimulator {
        doc /* ModelSim simulator integration. */

        comment sourceRef /* Source: src/DEMAConsulting.VHDLTest/Simulators/ModelSimSimulator.cs */
        comment testRef /* Test: test/DEMAConsulting.VHDLTest.Tests/Simulators/ModelSimSimulatorTests.cs */
        comment designRef /* Design: docs/design/vhdltest/simulators/modelsim-simulator.md */
        comment verificationRef /* Verification: docs/verification/vhdltest/simulators/modelsim-simulator.md */
        comment reqRef /* Requirements: docs/reqstream/vhdltest/simulators/modelsim-simulator.yaml */
    }
}
