package VHDLTest {
    part def NvcSimulator {
        doc /* NVC simulator integration. */

        comment sourceRef /* Source: src/DEMAConsulting.VHDLTest/Simulators/NvcSimulator.cs */
        comment testRef /* Test: test/DEMAConsulting.VHDLTest.Tests/Simulators/NvcSimulatorTests.cs */
        comment designRef /* Design: docs/design/vhdltest/simulators/nvc-simulator.md */
        comment verificationRef /* Verification: docs/verification/vhdltest/simulators/nvc-simulator.md */
        comment reqRef /* Requirements: docs/reqstream/vhdltest/simulators/nvc-simulator.yaml */
    }
}
