package VHDLTest {
    part def QuestaSimSimulator {
        doc /* QuestaSim simulator integration. */

        comment sourceRef /* Source: src/DEMAConsulting.VHDLTest/Simulators/QuestaSimSimulator.cs */
        comment testRef /* Test: test/DEMAConsulting.VHDLTest.Tests/Simulators/QuestaSimSimulatorTests.cs */
        comment designRef /* Design: docs/design/vhdltest/simulators/questasim-simulator.md */
        comment verificationRef /* Verification: docs/verification/vhdltest/simulators/questasim-simulator.md */
        comment reqRef /* Requirements: docs/reqstream/vhdltest/simulators/questasim-simulator.yaml */
    }
}
