package VHDLTest {
    part def VivadoSimulator {
        doc /* Vivado simulator integration. */

        comment sourceRef /* Source: src/DEMAConsulting.VHDLTest/Simulators/VivadoSimulator.cs */
        comment testRef /* Test: test/DEMAConsulting.VHDLTest.Tests/Simulators/VivadoSimulatorTests.cs */
        comment designRef /* Design: docs/design/vhdltest/simulators/vivado-simulator.md */
        comment verificationRef /* Verification: docs/verification/vhdltest/simulators/vivado-simulator.md */
        comment reqRef /* Requirements: docs/reqstream/vhdltest/simulators/vivado-simulator.yaml */
    }
}
